EnergyDeposition += ed_commInterface.o \
	ed_commInit.o \
	ed_commInitComm.o \
	ed_commFinalize.o \
	ed_commProgressTransport.o \
	ed_commIsTransportDone.o \
	ed_commIncrementDeadRays.o \
	ed_commHandleOffBlkRay.o \
	ed_commGetNewRays.o \
	ed_commSortParticles.o \
	ed_comm_sort_particles.o
