Particles += \
  Particles_sinkData.o \
  pt_sinkAccelSinksOnSinks.o \
  pt_sinkCorrectForPeriodicBCs.o \
  pt_sinkCreateParticle.o \
  pt_sinkDumpParticles.o \
  pt_sinkEwaldCorrection.o \
  pt_sinkFindList.o \
  pt_sinkGatherGlobal.o \
  pt_sinkGetSubCycleTimeStep.o \
  pt_sinkInterface.o \
  pt_sinkMergingAfterCreation.o \
  pt_sinkParticleMerging.o \
  Particles_sinkSumAttributes.o \
  pt_sinkPrepareEwald.o \
  pt_sinkSort.o
