Eos += eos_tabData.o                    	 \
           eos_tabBrowseIonmixTables.o           \
           eos_tabBrowseIonmix4Tables.o          \
           eos_tabBrowseTables.o                 \
           eos_tabFindTablePos.o                 \
           eos_tabGetSpeciesAnyTableData.o       \
           eos_tabGetSpeciesTabulatedData.o      \
           eos_tabInterface.o                    \
           eos_tabIonmix4.o                      \
           eos_tabLogOutsideCounts.o             \
           eos_tabReadIonmixTables.o             \
           eos_tabReadIonmix4Tables.o            \
           eos_tabReadTables.o                   \
           eos_tabUpdateOutsideCount.o           \
           eos_tabWriteSpeciesZFTable.o          \
           eos_tabWriteSpeciesENTable.o          \
           eos_tabWriteSpeciesHCTable.o          \
           eos_tabWriteSpeciesPRTable.o          \
           eos_tabWriteSpeciesEntrTable.o        \
           eos_tabWriteSpeciesTables.o           \
           eos_tabWriteTables.o                  \
           eos_tabZeroOutsideCounts.o
#           eos_tabGetSpeciesConstantOpacities.o  \
#           eos_tabWriteConstants.o               

