#	Makefile for FLASH code (RHD module)

Hydro += Hydro_data.o \
	hy_rhd_checkBoundaryValues.o \
	hy_rhd_conserveToPrimitive.o \
        hy_rhd_riemann.o \
	hy_rhd_setTstep.o \
	hy_rhd_enthalpy.o \
        hy_rhd_shock.o \
	hy_rhd_flux.o	\
	hy_rhd_sources.o \
        hy_rhd_hlle.o \
	hy_rhd_states.o \
	hy_rhd_maxChSpeed.o \
	hy_rhd_sweep.o \
        hy_rhd_pressureFunc.o \
	hy_rhd_primitiveToConserve.o \
	hy_rhd_reconstruct.o \
	hy_rhd_soundSpeed2.o \
	hy_rhd_interface.o 

